### ISSUE TITLE
Auto-night in Apple Books

### ISSUE THREAD

**Issue by dpopeck** [bartificer/taming-the-terminal#76] opened 2020-08-10 11:22 UTC
Enjoying the terminal book. the auto-night option in Books yields hard to read links in your text. I would hope/imagine/guess that there is a style sheet to change the links’s appearance. 
![48850C63-5064-4854-9B47-050633446B62](https://user-images.githubusercontent.com/69462157/89777685-25cae100-dada-11ea-9a0a-58e463e03162.jpeg)

**Comment by slonopotamus** [comment] 2020-08-11 13:36
I believe this is caused by https://github.com/asciidoctor/asciidoctor-epub3/issues/338 and was fixed in asciidoctor-epub3 1.5.0.alpha.18.

**Comment by hepabolu** [comment] 2020-08-13 20:46
Verified that this should fix the link color problem. @dpopeck Please check if it works for you. Thanks @slonopotamus for the fix.

**Closed by hepabolu** 2020-08-13 20:46 UTC
