### ISSUE TITLE
Links in the Table of Contents in dark mode not visible 

### ISSUE THREAD

**Issue by mermare** [bartificer/taming-the-terminal#86] opened 2020-08-21 19:54 UTC
See screenshot. This is in iOS Books app and book version 1.3.
![3C9D941A-040F-490A-81F9-7E34BA512558](https://user-images.githubusercontent.com/3846645/90929360-93261e00-e3c6-11ea-9347-73c6c76a9698.png)

*NOTE: This issue is fixed in the latest EPub version downloaded from GitHub and opened in Apple Books (iOS). v. 1.3 “Compiled: 2020-08-18 19-22-09”

**Comment by hepabolu** [comment] 2020-09-10 20:57
I can confirm it's like that in iOS Books and in iPadOS Books, but it's ok in Mac Books.
However, there is not much I can do. It looks like the problem lies with the Books version.

I filed an issue in the converter project: https://github.com/asciidoctor/asciidoctor-epub3/issues/366

**Comment by hepabolu** [comment] 2020-09-12 09:07
After researching a bit more I think I found a clue. The links in the Table of Contents are marked as 'visited' right away. And the ePub styles the visited links a dark grey.

**Comment by hepabolu** [comment] 2020-09-12 16:59
It was actually the color of 'visited' links that made the links very hard to read in Night mode. The fix changes the visited color to the original Apple Books color when in Night mode. Caveat: there is no visible difference between visited and unvisited links in Night mode anymore.

**Closed by hepabolu** 2020-09-12 16:59 UTC

**Comment by mermare** [comment] 2020-09-12 18:34
Thanks 😊
